# Created from an example found here
# https://github.com/iyassou/mpyaes

import mpyaes

key = mpyaes.generate_key(32)
# This key generated by above command and copied to TestDecrypt.py
print("key="+str(key))
print()
# IV = mpyaes.generate_IV(16)
# IV generated by above command and copied to TestDecrypt.py
IV=bytearray(b't\x1c\\\xb5g\xd9\xaf\x94\xbf\xf5^Rd\x8f\xfel')
print("IV="+str(IV))

